/******SQL_VARIANT_PROPERTY******/

SELECT SQL_VARIANT_PROPERTY('LA', 'BaseType') AS EX1
SELECT SQL_VARIANT_PROPERTY('2022-04-01', 'BaseType') AS EX2
SELECT SQL_VARIANT_PROPERTY(CAST('2022-04-01' AS DATE), 'BaseType') AS EX3
SELECT SQL_VARIANT_PROPERTY(10, 'BaseType') AS EX4
SELECT SQL_VARIANT_PROPERTY(10.0, 'BaseType') AS EX5
SELECT SQL_VARIANT_PROPERTY(CAST(10.0 AS INT), 'BaseType') AS EX6

SELECT CAST(10.9 AS INT) AS EX7

--Exercicio 1: Crie uma consulta juntando o texto: "O preco eh:" com o valor 30.99
SELECT 'O PRECO EH: ' + CAST(30.99 AS VARCHAR(50))

-- Exercicio 2: Adicione 1 dia a data 20/06/2021
SELECT CAST('2021-06-20' AS DATETIME) + 1